p8105_hw2_zc2691
================
Zhaohua Chunyu
2022-10-02

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(readxl)
library(dplyr)
```

``` r
subway_df = read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
                     col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>%
  janitor::clean_names() %>% 
  select(line:route11, entry:vending, ada, entrance_type) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
subway_df
```

    ## # A tibble: 1,868 × 20
    ##    line     station_…¹ stati…² stati…³ route1 route2 route3 route4 route5 route6
    ##    <chr>    <chr>        <dbl>   <dbl> <chr>  <chr>  <chr>  <chr>  <chr>  <chr> 
    ##  1 4 Avenue 25th St       40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  2 4 Avenue 25th St       40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  3 4 Avenue 36th St       40.7   -74.0 N      R      <NA>   <NA>   <NA>   <NA>  
    ##  4 4 Avenue 36th St       40.7   -74.0 N      R      <NA>   <NA>   <NA>   <NA>  
    ##  5 4 Avenue 36th St       40.7   -74.0 N      R      <NA>   <NA>   <NA>   <NA>  
    ##  6 4 Avenue 45th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  7 4 Avenue 45th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  8 4 Avenue 45th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  9 4 Avenue 45th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## 10 4 Avenue 53rd St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## # … with 1,858 more rows, 10 more variables: route7 <chr>, route8 <chr>,
    ## #   route9 <chr>, route10 <chr>, route11 <chr>, entry <lgl>, exit_only <chr>,
    ## #   vending <chr>, ada <lgl>, entrance_type <chr>, and abbreviated variable
    ## #   names ¹​station_name, ²​station_latitude, ³​station_longitude

``` r
subway_df %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 465 × 2
    ##    station_name             line    
    ##    <chr>                    <chr>   
    ##  1 25th St                  4 Avenue
    ##  2 36th St                  4 Avenue
    ##  3 45th St                  4 Avenue
    ##  4 53rd St                  4 Avenue
    ##  5 59th St                  4 Avenue
    ##  6 77th St                  4 Avenue
    ##  7 86th St                  4 Avenue
    ##  8 95th St                  4 Avenue
    ##  9 9th St                   4 Avenue
    ## 10 Atlantic Av-Barclays Ctr 4 Avenue
    ## # … with 455 more rows

``` r
subway_df %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # … with 74 more rows

``` r
subway_df %>% 
  pivot_longer(
    route1:route11,
    names_to = "routenum",
    values_to = "route") %>% 
  filter(route == "A") %>% 
  select (line, station_name) %>% 
  distinct
```

    ## # A tibble: 60 × 2
    ##    line            station_name                 
    ##    <chr>           <chr>                        
    ##  1 42nd St Shuttle Times Square                 
    ##  2 8 Avenue        125th St                     
    ##  3 8 Avenue        145th St                     
    ##  4 8 Avenue        14th St                      
    ##  5 8 Avenue        168th St - Washington Heights
    ##  6 8 Avenue        175th St                     
    ##  7 8 Avenue        181st St                     
    ##  8 8 Avenue        190th St                     
    ##  9 8 Avenue        34th St                      
    ## 10 8 Avenue        42nd St                      
    ## # … with 50 more rows

``` r
subway_df %>% 
  pivot_longer(
    route1:route11,
    names_to = "routenum",
    values_to = "route") %>% 
  filter(route == "A", ada == TRUE) %>% 
  select (line, station_name) %>% 
  distinct
```

    ## # A tibble: 17 × 2
    ##    line             station_name                 
    ##    <chr>            <chr>                        
    ##  1 8 Avenue         14th St                      
    ##  2 8 Avenue         168th St - Washington Heights
    ##  3 8 Avenue         175th St                     
    ##  4 8 Avenue         34th St                      
    ##  5 8 Avenue         42nd St                      
    ##  6 8 Avenue         59th St                      
    ##  7 8 Avenue         Inwood - 207th St            
    ##  8 8 Avenue         West 4th St                  
    ##  9 8 Avenue         World Trade Center           
    ## 10 Broadway         Times Square-42nd St         
    ## 11 Broadway-7th Ave 59th St-Columbus Circle      
    ## 12 Broadway-7th Ave Times Square                 
    ## 13 Canarsie         8th Av                       
    ## 14 Franklin         Franklin Av                  
    ## 15 Fulton           Euclid Av                    
    ## 16 Fulton           Franklin Av                  
    ## 17 Rockaway         Howard Beach

## Probelm 2

``` r
mr_trash_df =  read_excel("data/Trash Wheel Collection Data.xlsx", sheet = 1) %>% 
  janitor::clean_names() %>% 
  select(dumpster:homes_powered) %>% 
  drop_na() %>% 
  mutate(year = as.character(year)) %>% 
  mutate(weight_tons = round(weight_tons, digit = 0)) %>% 
  mutate(weight_tons = as.integer(weight_tons)) %>% 
  mutate(id = "Mr.Trash Wheel") %>% 
  select(id, dumpster:homes_powered)
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
mr_trash_df
```

    ## # A tibble: 486 × 15
    ##    id    dumps…¹ month year  date                weigh…² volum…³ plast…⁴ polys…⁵
    ##    <chr>   <dbl> <chr> <chr> <dttm>                <int>   <dbl>   <dbl>   <dbl>
    ##  1 Mr.T…       1 May   2014  2014-05-16 00:00:00       4      18    1450    1820
    ##  2 Mr.T…       2 May   2014  2014-05-16 00:00:00       3      13    1120    1030
    ##  3 Mr.T…       3 May   2014  2014-05-16 00:00:00       3      15    2450    3100
    ##  4 Mr.T…       4 May   2014  2014-05-17 00:00:00       3      15    2380    2730
    ##  5 Mr.T…       5 May   2014  2014-05-17 00:00:00       4      18     980     870
    ##  6 Mr.T…       6 May   2014  2014-05-20 00:00:00       3      13    1430    2140
    ##  7 Mr.T…       7 May   2014  2014-05-21 00:00:00       2       8     910    1090
    ##  8 Mr.T…       8 May   2014  2014-05-28 00:00:00       4      16    3580    4310
    ##  9 Mr.T…       9 June  2014  2014-06-05 00:00:00       3      14    2400    2790
    ## 10 Mr.T…      10 June  2014  2014-06-11 00:00:00       4      18    1340    1730
    ## # … with 476 more rows, 6 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <dbl>, homes_powered <dbl>, and abbreviated variable names
    ## #   ¹​dumpster, ²​weight_tons, ³​volume_cubic_yards, ⁴​plastic_bottles,
    ## #   ⁵​polystyrene

``` r
prof_trash_df =  read_excel("data/Trash Wheel Collection Data.xlsx", sheet = 2) %>% 
  janitor::clean_names() %>% 
  select(dumpster:homes_powered) %>% 
  drop_na() %>% 
  mutate(year = as.character(year)) %>% 
  mutate(weight_tons = round(weight_tons, digit = 0)) %>% 
  mutate(weight_tons = as.integer(weight_tons)) %>% 
  mutate(id = "Professor Trash Wheel") %>% 
  select(id, dumpster:homes_powered)
prof_trash_df
```

    ## # A tibble: 82 × 14
    ##    id    dumps…¹ month year  date                weigh…² volum…³ plast…⁴ polys…⁵
    ##    <chr>   <dbl> <chr> <chr> <dttm>                <int>   <dbl>   <dbl>   <dbl>
    ##  1 Prof…       1 Janu… 2017  2017-01-02 00:00:00       2      15    1950    6080
    ##  2 Prof…       2 Janu… 2017  2017-01-30 00:00:00       2      15    9540   11230
    ##  3 Prof…       3 Febr… 2017  2017-02-26 00:00:00       2      18    8350    9210
    ##  4 Prof…       4 Febr… 2017  2017-02-26 00:00:00       4      15    8590    1030
    ##  5 Prof…       5 Febr… 2017  2017-02-28 00:00:00       1      15    7830    9950
    ##  6 Prof…       6 March 2017  2017-03-30 00:00:00       2      15    8210   10340
    ##  7 Prof…       7 April 2017  2017-04-01 00:00:00       2      15    9830   11020
    ##  8 Prof…       8 April 2017  2017-04-20 00:00:00       2      15    9240    8760
    ##  9 Prof…       9 May   2017  2017-05-10 00:00:00       3      15    9540    8810
    ## 10 Prof…      10 May   2017  2017-05-26 00:00:00       3      15    8230    7800
    ## # … with 72 more rows, 5 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   homes_powered <dbl>, and abbreviated variable names ¹​dumpster,
    ## #   ²​weight_tons, ³​volume_cubic_yards, ⁴​plastic_bottles, ⁵​polystyrene

``` r
trash_df = left_join(mr_trash_df, prof_trash_df, by = c("year","month"))
```

``` r
summary(mr_trash_df) ## size of df: 486* 15
```

    ##       id               dumpster        month               year          
    ##  Length:486         Min.   :  1.0   Length:486         Length:486        
    ##  Class :character   1st Qu.:122.2   Class :character   Class :character  
    ##  Mode  :character   Median :243.5   Mode  :character   Mode  :character  
    ##                     Mean   :243.5                                        
    ##                     3rd Qu.:364.8                                        
    ##                     Max.   :486.0                                        
    ##       date                         weight_tons    volume_cubic_yards
    ##  Min.   :1900-01-20 00:00:00.00   Min.   :1.000   Min.   : 7.00     
    ##  1st Qu.:2016-02-20 12:00:00.00   1st Qu.:3.000   1st Qu.:15.00     
    ##  Median :2018-04-17 12:00:00.00   Median :3.000   Median :15.00     
    ##  Mean   :2017-10-07 18:54:48.89   Mean   :3.189   Mean   :15.38     
    ##  3rd Qu.:2019-10-04 06:00:00.00   3rd Qu.:4.000   3rd Qu.:15.00     
    ##  Max.   :2021-08-20 00:00:00.00   Max.   :6.000   Max.   :20.00     
    ##  plastic_bottles   polystyrene   cigarette_butts  glass_bottles   
    ##  Min.   : 210.0   Min.   : 120   Min.   :   980   Min.   :  0.00  
    ##  1st Qu.: 992.5   1st Qu.: 880   1st Qu.:  4425   1st Qu.: 10.00  
    ##  Median :1880.0   Median :1495   Median :  9000   Median : 18.00  
    ##  Mean   :1939.5   Mean   :1827   Mean   : 23126   Mean   : 22.14  
    ##  3rd Qu.:2647.5   3rd Qu.:2648   3rd Qu.: 32000   3rd Qu.: 32.00  
    ##  Max.   :5960.0   Max.   :6540   Max.   :310000   Max.   :110.00  
    ##   grocery_bags    chip_bags     sports_balls   homes_powered  
    ##  Min.   :  50   Min.   : 180   Min.   : 0.00   Min.   : 0.00  
    ##  1st Qu.: 420   1st Qu.: 785   1st Qu.: 6.00   1st Qu.:39.54  
    ##  Median : 790   Median :1200   Median :10.00   Median :51.17  
    ##  Mean   :1064   Mean   :1507   Mean   :12.09   Mean   :45.98  
    ##  3rd Qu.:1522   3rd Qu.:2138   3rd Qu.:16.00   3rd Qu.:59.12  
    ##  Max.   :3750   Max.   :5085   Max.   :56.00   Max.   :93.67

``` r
summary(prof_trash_df) ## size of df: 82 * 14
```

    ##       id               dumpster        month               year          
    ##  Length:82          Min.   : 1.00   Length:82          Length:82         
    ##  Class :character   1st Qu.:21.25   Class :character   Class :character  
    ##  Mode  :character   Median :41.50   Mode  :character   Mode  :character  
    ##                     Mean   :41.50                                        
    ##                     3rd Qu.:61.75                                        
    ##                     Max.   :82.00                                        
    ##       date                         weight_tons    volume_cubic_yards
    ##  Min.   :2017-01-02 00:00:00.00   Min.   :1.000   Min.   : 6.00     
    ##  1st Qu.:2018-03-02 06:00:00.00   1st Qu.:2.000   1st Qu.:15.00     
    ##  Median :2018-12-14 12:00:00.00   Median :2.000   Median :15.00     
    ##  Mean   :2019-03-03 19:54:08.77   Mean   :2.024   Mean   :14.65     
    ##  3rd Qu.:2020-05-02 00:00:00.00   3rd Qu.:2.000   3rd Qu.:15.00     
    ##  Max.   :2021-08-20 00:00:00.00   Max.   :4.000   Max.   :18.00     
    ##  plastic_bottles  polystyrene    cigarette_butts glass_bottles  
    ##  Min.   : 657    Min.   :  800   Min.   : 6000   Min.   : 0.00  
    ##  1st Qu.:4014    1st Qu.: 2962   1st Qu.: 8025   1st Qu.: 6.00  
    ##  Median :5700    Median : 4365   Median :11000   Median :12.00  
    ##  Mean   :5601    Mean   : 5254   Mean   :13250   Mean   :12.89  
    ##  3rd Qu.:7538    3rd Qu.: 8138   3rd Qu.:17450   3rd Qu.:18.75  
    ##  Max.   :9830    Max.   :11528   Max.   :33320   Max.   :32.00  
    ##   grocery_bags     chip_bags     homes_powered  
    ##  Min.   :  540   Min.   : 2900   Min.   :10.17  
    ##  1st Qu.:  980   1st Qu.: 5150   1st Qu.:26.33  
    ##  Median : 1368   Median : 7200   Median :31.08  
    ##  Mean   : 2993   Mean   : 8686   Mean   :33.04  
    ##  3rd Qu.: 2675   3rd Qu.:12400   3rd Qu.:40.88  
    ##  Max.   :13450   Max.   :20100   Max.   :62.00

``` r
mr_trash_df[1,] ##Examples of an observation of the dataframe
```

    ## # A tibble: 1 × 15
    ##   id     dumps…¹ month year  date                weigh…² volum…³ plast…⁴ polys…⁵
    ##   <chr>    <dbl> <chr> <chr> <dttm>                <int>   <dbl>   <dbl>   <dbl>
    ## 1 Mr.Tr…       1 May   2014  2014-05-16 00:00:00       4      18    1450    1820
    ## # … with 6 more variables: cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   grocery_bags <dbl>, chip_bags <dbl>, sports_balls <dbl>,
    ## #   homes_powered <dbl>, and abbreviated variable names ¹​dumpster,
    ## #   ²​weight_tons, ³​volume_cubic_yards, ⁴​plastic_bottles, ⁵​polystyrene

``` r
prof_trash_df[1,] ##Examples of an observation of the dataframe
```

    ## # A tibble: 1 × 14
    ##   id     dumps…¹ month year  date                weigh…² volum…³ plast…⁴ polys…⁵
    ##   <chr>    <dbl> <chr> <chr> <dttm>                <int>   <dbl>   <dbl>   <dbl>
    ## 1 Profe…       1 Janu… 2017  2017-01-02 00:00:00       2      15    1950    6080
    ## # … with 5 more variables: cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   grocery_bags <dbl>, chip_bags <dbl>, homes_powered <dbl>, and abbreviated
    ## #   variable names ¹​dumpster, ²​weight_tons, ³​volume_cubic_yards,
    ## #   ⁴​plastic_bottles, ⁵​polystyrene

``` r
prof_trash_df %>% 
  select(weight_tons) %>% 
  pull(weight_tons) %>% 
  sum() ## Calculate the total weight of trash collected by Professor Trash Wheel
```

    ## [1] 166

``` r
mr_trash_df %>% 
  select(year, sports_balls) %>% 
  filter(year == "2020") %>%
  pull(sports_balls) %>% 
  sum() ## Calculate the total number of sports balls collected by Mr. Trash Wheel in 2020
```

    ## [1] 856

There are 486 observations in *mr_trash_df* dataset and 82 observations
in *prof_trash_df* dataset Each table contains variables of dumpter
number (`dumpster`), date of collection (`date`), amount of total
litter(`weight_tons` & `volume_cubic_yards`) and different litter types
(such as `plastic bottles`, `cigarette butts`, `sport balls`, and etc.)
The *trash_df* combine and compare the dumpsters data of *mr_trash_df*
and *prof_trash_df* that happened on the same date. The total weight of
trash collected by Professor Trash Wheel was 166 tons. The total number
of sports balls collected by Mr. Trash Wheel in 2020 was 856.

## Problem 3

``` r
pols_mon_raw = read_csv("./data/fivethirtyeight_datasets/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, c("year", "month", "day")) %>% 
  mutate(month = as.numeric(month)) %>% 
  mutate(month = month.name[month]) %>% 
  mutate(prez_gop = replace(prez_gop, prez_gop == 1, "gop")) %>%
  mutate(prez_gop = replace(prez_gop, prez_gop == 0, "dem")) %>%
  mutate(prez_dem = replace(prez_dem, prez_dem == 1, "dem")) %>%
  mutate(prez_dem = replace(prez_gop, prez_gop == 0, "gop")) %>%
  pivot_longer(
    c(prez_dem, prez_gop),
    names_to = "party",
    values_to = "president") %>% 
  select(year,month, president, gov_gop:rep_gop, gov_dem:rep_dem)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
rows = nrow(pols_mon_raw)
odd_rows = seq_len(rows) %% 2
pols_mon = pols_mon_raw[odd_rows == 1, ]
pols_mon
```

    ## # A tibble: 822 × 9
    ##    year  month     president gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem
    ##    <chr> <chr>     <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ##  1 1947  January   dem            23      51     253      23      45     198
    ##  2 1947  February  dem            23      51     253      23      45     198
    ##  3 1947  March     dem            23      51     253      23      45     198
    ##  4 1947  April     dem            23      51     253      23      45     198
    ##  5 1947  May       dem            23      51     253      23      45     198
    ##  6 1947  June      dem            23      51     253      23      45     198
    ##  7 1947  July      dem            23      51     253      23      45     198
    ##  8 1947  August    dem            23      51     253      23      45     198
    ##  9 1947  September dem            23      51     253      23      45     198
    ## 10 1947  October   dem            23      51     253      23      45     198
    ## # … with 812 more rows

``` r
snp = read_csv("./data/fivethirtyeight_datasets/snp.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date(date, format = "%m/%d/%y")) %>% 
  separate(date, c("year", "month", "day")) %>% 
  mutate(month = as.numeric(month)) %>% 
  mutate(month = month.name[month]) %>% 
  select(year,month, close) 
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp
```

    ## # A tibble: 787 × 3
    ##    year  month    close
    ##    <chr> <chr>    <dbl>
    ##  1 2015  July     2080.
    ##  2 2015  June     2063.
    ##  3 2015  May      2107.
    ##  4 2015  April    2086.
    ##  5 2015  March    2068.
    ##  6 2015  February 2104.
    ##  7 2015  January  1995.
    ##  8 2014  December 2059.
    ##  9 2014  November 2068.
    ## 10 2014  October  2018.
    ## # … with 777 more rows

``` r
unemp = read_csv("./data/fivethirtyeight_datasets/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "unemp_perc"
  ) %>% 
  mutate(year = as.character(year)) %>% 
  mutate(month = replace(month, month == "jan", "January")) %>% 
  mutate(month = replace(month, month == "feb", "February")) %>% 
  mutate(month = replace(month, month == "mar", "March")) %>% 
  mutate(month = replace(month, month == "apr", "April")) %>%
  mutate(month = replace(month, month == "may", "May")) %>% 
  mutate(month = replace(month, month == "jun", "June")) %>% 
  mutate(month = replace(month, month == "jul", "July")) %>% 
  mutate(month= replace(month, month == "aug", "August")) %>% 
  mutate(month = replace(month, month == "sep", "September")) %>% 
  mutate(month = replace(month, month == "oct", "October")) %>% 
  mutate(month = replace(month, month == "nov", "November")) %>% 
  mutate(month = replace(month, month == "dec", "December")) 
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemp
```

    ## # A tibble: 816 × 3
    ##    year  month     unemp_perc
    ##    <chr> <chr>          <dbl>
    ##  1 1948  January          3.4
    ##  2 1948  February         3.8
    ##  3 1948  March            4  
    ##  4 1948  April            3.9
    ##  5 1948  May              3.5
    ##  6 1948  June             3.6
    ##  7 1948  July             3.6
    ##  8 1948  August           3.9
    ##  9 1948  September        3.8
    ## 10 1948  October          3.7
    ## # … with 806 more rows

``` r
pols_mon_snp = left_join(pols_mon, snp, by = c("year", "month"))
pols_mon_snp
```

    ## # A tibble: 822 × 10
    ##    year  month     presi…¹ gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem close
    ##    <chr> <chr>     <chr>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <dbl>
    ##  1 1947  January   dem          23      51     253      23      45     198    NA
    ##  2 1947  February  dem          23      51     253      23      45     198    NA
    ##  3 1947  March     dem          23      51     253      23      45     198    NA
    ##  4 1947  April     dem          23      51     253      23      45     198    NA
    ##  5 1947  May       dem          23      51     253      23      45     198    NA
    ##  6 1947  June      dem          23      51     253      23      45     198    NA
    ##  7 1947  July      dem          23      51     253      23      45     198    NA
    ##  8 1947  August    dem          23      51     253      23      45     198    NA
    ##  9 1947  September dem          23      51     253      23      45     198    NA
    ## 10 1947  October   dem          23      51     253      23      45     198    NA
    ## # … with 812 more rows, and abbreviated variable name ¹​president

``` r
pols_mon_snp_unemp = left_join(pols_mon_snp, unemp, by = c("year", "month"))
pols_mon_snp_unemp
```

    ## # A tibble: 822 × 11
    ##    year  month     presi…¹ gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem close
    ##    <chr> <chr>     <chr>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <dbl>
    ##  1 1947  January   dem          23      51     253      23      45     198    NA
    ##  2 1947  February  dem          23      51     253      23      45     198    NA
    ##  3 1947  March     dem          23      51     253      23      45     198    NA
    ##  4 1947  April     dem          23      51     253      23      45     198    NA
    ##  5 1947  May       dem          23      51     253      23      45     198    NA
    ##  6 1947  June      dem          23      51     253      23      45     198    NA
    ##  7 1947  July      dem          23      51     253      23      45     198    NA
    ##  8 1947  August    dem          23      51     253      23      45     198    NA
    ##  9 1947  September dem          23      51     253      23      45     198    NA
    ## 10 1947  October   dem          23      51     253      23      45     198    NA
    ## # … with 812 more rows, 1 more variable: unemp_perc <dbl>, and abbreviated
    ## #   variable name ¹​president

``` r
summary(pols_mon) ## size of df: 822* 9
```

    ##      year              month            president            gov_gop     
    ##  Length:822         Length:822         Length:822         Min.   :12.00  
    ##  Class :character   Class :character   Class :character   1st Qu.:18.00  
    ##  Mode  :character   Mode  :character   Mode  :character   Median :22.00  
    ##                                                           Mean   :22.48  
    ##                                                           3rd Qu.:28.00  
    ##                                                           Max.   :34.00  
    ##     sen_gop        rep_gop         gov_dem        sen_dem         rep_dem   
    ##  Min.   :32.0   Min.   :141.0   Min.   :17.0   Min.   :44.00   Min.   :188  
    ##  1st Qu.:42.0   1st Qu.:176.0   1st Qu.:22.0   1st Qu.:48.00   1st Qu.:211  
    ##  Median :46.0   Median :195.0   Median :28.0   Median :53.00   Median :250  
    ##  Mean   :46.1   Mean   :194.9   Mean   :27.2   Mean   :54.41   Mean   :245  
    ##  3rd Qu.:51.0   3rd Qu.:222.0   3rd Qu.:32.0   3rd Qu.:58.00   3rd Qu.:268  
    ##  Max.   :56.0   Max.   :253.0   Max.   :41.0   Max.   :71.00   Max.   :301

``` r
summary(snp) ## size of df: 787 * 3
```

    ##      year              month               close        
    ##  Length:787         Length:787         Min.   :  17.05  
    ##  Class :character   Class :character   1st Qu.:  83.73  
    ##  Mode  :character   Mode  :character   Median : 138.53  
    ##                                        Mean   : 474.89  
    ##                                        3rd Qu.: 941.79  
    ##                                        Max.   :2107.39

``` r
summary(unemp) ## size of df: 816 * 3
```

    ##      year              month             unemp_perc   
    ##  Length:816         Length:816         Min.   : 2.50  
    ##  Class :character   Class :character   1st Qu.: 4.70  
    ##  Mode  :character   Mode  :character   Median : 5.60  
    ##                                        Mean   : 5.83  
    ##                                        3rd Qu.: 6.90  
    ##                                        Max.   :10.80  
    ##                                        NA's   :6

``` r
summary(pols_mon_snp_unemp) ## size of df: 822* 11
```

    ##      year              month            president            gov_gop     
    ##  Length:822         Length:822         Length:822         Min.   :12.00  
    ##  Class :character   Class :character   Class :character   1st Qu.:18.00  
    ##  Mode  :character   Mode  :character   Mode  :character   Median :22.00  
    ##                                                           Mean   :22.48  
    ##                                                           3rd Qu.:28.00  
    ##                                                           Max.   :34.00  
    ##                                                                          
    ##     sen_gop        rep_gop         gov_dem        sen_dem         rep_dem   
    ##  Min.   :32.0   Min.   :141.0   Min.   :17.0   Min.   :44.00   Min.   :188  
    ##  1st Qu.:42.0   1st Qu.:176.0   1st Qu.:22.0   1st Qu.:48.00   1st Qu.:211  
    ##  Median :46.0   Median :195.0   Median :28.0   Median :53.00   Median :250  
    ##  Mean   :46.1   Mean   :194.9   Mean   :27.2   Mean   :54.41   Mean   :245  
    ##  3rd Qu.:51.0   3rd Qu.:222.0   3rd Qu.:32.0   3rd Qu.:58.00   3rd Qu.:268  
    ##  Max.   :56.0   Max.   :253.0   Max.   :41.0   Max.   :71.00   Max.   :301  
    ##                                                                             
    ##      close           unemp_perc   
    ##  Min.   :  63.54   Min.   : 2.50  
    ##  1st Qu.: 114.69   1st Qu.: 4.70  
    ##  Median : 413.37   Median : 5.60  
    ##  Mean   : 643.34   Mean   : 5.83  
    ##  3rd Qu.:1146.78   3rd Qu.: 6.90  
    ##  Max.   :2107.39   Max.   :10.80  
    ##  NA's   :264       NA's   :12

*pols_mon* dataset contains 822 observations of 9 variables related to
the number of national politicians who are democratic or republican at
any given time: `year` & `month`(year and month of the count),
`president`(the indicator of whether the president was democratic or
republican), `gov_gop`(the number of republican governors on the
associated date), `sen_gop`(the number of republican senators on the
associated date), `rep_gop`(the number of republican representatives on
the associated date), etc.

*snp* contains 787 observations of 3 variables related to Standard &
Poor’s stock market index (S&P):`year` & `month`, `close`(the closing
values of the S&P stock index on the associated date). The max closing
value is 2107.39; the min is 17.05; and the mean is 474.89.

*unemp* contains 816 observations of 3 variables:`year` & `month`,
`unemp_perc`(percentage of unemployment in each month of the associated
year). The max unemployment percentage is 10.80%; the min is 2.50%; and
the mean is 5.83.

The resulting dataset *pols_mon_snp_unemp* contains 816 observations of
11 variables obtained from the former three tables combined together.
The range of year is from 1969 to 2015. The key variables include `year`
& `month`, `president`, `gov_gop`, `sen_gop`, `rep_gop`, `close`, and
`unemp_perc`. The mean close value is 241.1 and the mean unemployment
percentage is 5.83.
